site_name: Biru is my Guru

nav:
   - Home:
      - 'Front of House': intro_page/index.md
      - 'Back of House' : intro_page/index2.md
   - Where are they?:
       - 'The Bar': where_is_page/TheBar.md
       - 'Under the Sections': where_is_page/Sections.md
   - How to?:
      - 'Float': how_to_page/float.md


theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: blue grey
      accent: light blue
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
      accent: light blue        

  font:
    text: Bitter

  language: en
  
  logo: assets/logo/logo.png
  favicon: assets/logo/logo.png
  
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - toc.follow
    - navigation.top
    
  plugins:
    - typeset

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/birat-jung-thapa/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/birat_jg/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


